Repository ESCOMP/atmospheric_physics, pull requests merged in 2024-10, with the labels that each got.

#126 Move suite and scheme files to new directories
  doc/ChangeLog
  schemes/cam_diagnostics/tropopause_diagnostics.F90
  schemes/cam_diagnostics/tropopause_diagnostics.meta
  schemes/dry_adiabatic_adjust/dadadj.F90
  schemes/dry_adiabatic_adjust/dadadj.meta
  schemes/dry_adiabatic_adjust/dadadj_apply_qv_tendency.F90
  schemes/dry_adiabatic_adjust/dadadj_apply_qv_tendency.meta
  schemes/dry_adiabatic_adjust/dadadj_namelist.xml
  schemes/held_suarez/held_suarez_1994.F90
  schemes/held_suarez/held_suarez_1994.meta
  schemes/kessler/kessler.F90
  schemes/kessler/kessler.meta
  schemes/kessler/kessler_update.F90
  schemes/kessler/kessler_update.meta
  schemes/musica/micm/micm_util.F90
  schemes/musica/micm/musica_ccpp_micm.F90
  schemes/musica/musica_ccpp.F90
  schemes/musica/musica_ccpp.meta
  schemes/musica/musica_ccpp_namelist.xml
  schemes/musica/musica_ccpp_util.F90
  schemes/musica/tuvx/musica_ccpp_tuvx.F90
  schemes/tj2016/tj2016_precip.F90
  schemes/tj2016/tj2016_precip.meta
  schemes/tj2016/tj2016_sfc_pbl_hs.F90
  schemes/tj2016/tj2016_sfc_pbl_hs.meta
  schemes/tropopause_find/tropopause_find.F90
  schemes/tropopause_find/tropopause_find.meta
  schemes/utilities/geopotential_temp.F90
  schemes/utilities/geopotential_temp.meta
  schemes/utilities/physics_tendency_updaters.F90
  schemes/utilities/physics_tendency_updaters.meta
  schemes/utilities/qneg.F90
  schemes/utilities/qneg.meta
  schemes/utilities/qneg_namelist.xml
  schemes/utilities/state_converters.F90
  schemes/utilities/state_converters.meta
  schemes/utilities/static_energy.F90
  schemes/utilities/static_energy.meta
  schemes/zhang_mcfarlane/zm_conv_convtran.F90
  schemes/zhang_mcfarlane/zm_conv_convtran.meta
  schemes/zhang_mcfarlane/zm_conv_evap.F90
  schemes/zhang_mcfarlane/zm_conv_evap.meta
  schemes/zhang_mcfarlane/zm_conv_momtran.F90
  schemes/zhang_mcfarlane/zm_conv_momtran.meta
  schemes/zhang_mcfarlane/zm_convr.F90
  schemes/zhang_mcfarlane/zm_convr.meta
  suites/suite_cam4.xml
  suites/suite_cam6.xml
  suites/suite_cam6_silhs.xml
  suites/suite_cam7.xml
  suites/suite_held_suarez_1994.xml
  suites/suite_kessler.xml
  suites/suite_musica.xml
  suites/suite_tj2016.xml
  test/CMakeLists.txt
  test/test_suites/suite_dry_adiabatic_adjust.xml
  test/test_suites/suite_tj2016_precip.xml
  test/test_suites/suite_tj2016_sfc_pbl_hs.xml
  test/test_suites/suite_tropopause_find.xml
Labels: cleanup

#129 Add 'Changelog' updates missed in previous PR.
  doc/ChangeLog
Labels: documentation

#135 Implement ccpp_const_get_index in to_be_ccppized to avoid circular dependencies
  doc/ChangeLog
  to_be_ccppized/ccpp_const_utils.F90
Labels: enhancement
